//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor_OpenBMCLAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Auth {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Auth() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor_OpenBMCLAPI.Resources.Auth", typeof(Auth).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Back home 的本地化字符串。
        /// </summary>
        internal static string back_home {
            get {
                return ResourceManager.GetString("back_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name or password is invalid 的本地化字符串。
        /// </summary>
        internal static string invalid {
            get {
                return ResourceManager.GetString("invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to login, Please check your user name and password. 的本地化字符串。
        /// </summary>
        internal static string login_failed {
            get {
                return ResourceManager.GetString("login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We&apos;re sorry, but we can&apos;t find the page you&apos;re visiting, please wait a moment, or contact the admin. 的本地化字符串。
        /// </summary>
        internal static string notfound_intro {
            get {
                return ResourceManager.GetString("notfound_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oops! The page you are visiting is not exists 的本地化字符串。
        /// </summary>
        internal static string notfound_title {
            get {
                return ResourceManager.GetString("notfound_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are creating a user. Once created, this user will have full authority to operate the node, including access to and store sensitive information, so please be cautious. 的本地化字符串。
        /// </summary>
        internal static string register_intro {
            get {
                return ResourceManager.GetString("register_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        internal static string register_title {
            get {
                return ResourceManager.GetString("register_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not currently logged in, but the page you are visiting requires administrator privileges, so please log in first. 的本地化字符串。
        /// </summary>
        internal static string unauth_intro {
            get {
                return ResourceManager.GetString("unauth_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oops! You are not logged in 的本地化字符串。
        /// </summary>
        internal static string unauth_title {
            get {
                return ResourceManager.GetString("unauth_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name: 的本地化字符串。
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
